version: "3"

services:
  mongodb:
    image: mongo:4.4-bionic
    restart: always
    env_file:
    - .mongoenv
    restart: always
  modmail:
    image: modmail:latest
    build:
      context: ./modmail
    env_file:
    - .env
    - .mongo_url
    restart: always
  logviewer:
    image: logviewer:latest
    build:
      context: ./logviewer
    env_file:
    - .mongo_url
    restart: always

