version: "3"

services:
  mongodb:
    image: mongo:4.4-bionic
    restart: always
    env_file:
    restart: always
    volumes:
      - /srv/modmail-db:/data/db
  modmail:
    image: modmail:latest
    build:
      context: ./modmail
    env_file:
    - .env
    restart: always
  logviewer:
    image: logviewer:latest
    build:
      context: ./logviewer
    env_file:
    restart: always
    ports:
      - 8000:8000

